name: API Test Automation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  api-tests:
    name: Run API Tests (${{ github.event.inputs.environment || 'dev' }})
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Run API tests
        run: npx playwright test
        env:
          ENV: ${{ github.event.inputs.environment || 'dev' }}
          REQRES_API_KEY: ${{ secrets[format('REQRES_API_KEY_{0}', github.event.inputs.environment || 'dev')] || secrets.REQRES_API_KEY }}
          BASE_URL: https://reqres.in/api/test-suite/collections/users

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-api-report-${{ github.event.inputs.environment || 'dev' }}
          path: playwright-report/
          retention-days: 30

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-logs-${{ github.event.inputs.environment || 'dev' }}
          path: logs/
          retention-days: 14
